#!/bin/bash
borders \
  style=round \
  hidpi=on \
  width=5.0 \
  active_color="gradient(top_left=0xff89b4fa,bottom_right=0xffcba6f7)" \
  inactive_color=0x00000000 \
  blacklist="Finder,Notification Center,Control Center"
